### ISSUE TITLE
Unable to post new conversation after 6.1 upgrade

### ISSUE THREAD

**Issue by ghost** [meldsolutions/Meld-Forums#7]
Hey Grant,

I just updated to 6.1 and i'm noticing something odd. I don't know a ton about what changed, but I think that form validation changed and might be interfering with meld's postings. I see a javascript error when posting, see screen shot...

This happens upon clicking the submit button. It looks like the AJAX request went through okay (the 200) but then the function call fails. Could you take a look?

Thanks!
![meld-error](https://f.cloud.github.com/assets/450046/2131783/8c116ad0-92a5-11e3-8c07-548d4de77ef8.png)

**Comment by ghost** [comment]
Oh - a little more info if you need it - this is on our Dev for IHS - let me know if you need login info or anything :)

**Comment by grantshepert** [comment]
This has been fixed in latest commits. As no validation beyond "required" was required, this has been removed from the theme module files:

 onsubmit="return validate(this);"

... this should be removed from any custom themes for 6.1 deployments. Further updates may re-add pre/post 6.1 validation as well.
